/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef VIDEOSPIELTEST_PRIVATE_H
#define VIDEOSPIELTEST_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.7.5.737"
#define VER_MAJOR	1
#define VER_MINOR	7
#define VER_RELEASE	5
#define VER_BUILD	737
#define COMPANY_NAME	"MauProductions"
#define FILE_VERSION	"1.7.5.737"
#define FILE_DESCRIPTION	"It's a Snake"
#define INTERNAL_NAME	"project K‰sesoﬂe"
#define LEGAL_COPYRIGHT	"(C) Mau"
#define LEGAL_TRADEMARKS	"MauTrademarks"
#define ORIGINAL_FILENAME	"Snake"
#define PRODUCT_NAME	"SNAAAAAAKEEE!"
#define PRODUCT_VERSION	"1.7.5.737"

#endif /*VIDEOSPIELTEST_PRIVATE_H*/
