/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef VIDEOSPIELTEST_PRIVATE_H
#define VIDEOSPIELTEST_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.6.3.487"
#define VER_MAJOR	1
#define VER_MINOR	6
#define VER_RELEASE	3
#define VER_BUILD	487
#define COMPANY_NAME	"MauProductions"
#define FILE_VERSION	"1.6.3.487"
#define FILE_DESCRIPTION	"It's a Snake"
#define INTERNAL_NAME	"project K‰sesoﬂe"
#define LEGAL_COPYRIGHT	"(C) Mau"
#define LEGAL_TRADEMARKS	"MauTrademarks"
#define ORIGINAL_FILENAME	"Snake"
#define PRODUCT_NAME	"SNAAAAAAKEEE!"
#define PRODUCT_VERSION	"1.6.3.487"

#endif /*VIDEOSPIELTEST_PRIVATE_H*/
